title: "Programming Lessons & Visual Projects"
description: "My curated tutorials and creative coding experiments"
# the subpath of your site, e.g. /blog — leave empty if publishing to USERNAME.github.io
baseurl: ""
# the base hostname & protocol for your site
url: "https://YOUR_GITHUB_USERNAME.github.io"

markdown: kramdown
highlighter: rouge

# GitHub Pages (as of 2025‑01‑30) runs Jekyll 3.9.5  — compatible settings below
theme: null

plugins:
  - jekyll-feed
  - jekyll-sitemap

collections:
  lessons:
    output: true
    permalink: /lessons/:title/
  projects:
    output: true
    permalink: /projects/:title/

defaults:
  - scope:
      path: ""
      type: lessons
    values:
      layout: lesson
      nav_section: lessons
  - scope:
      path: ""
      type: projects
    values:
      layout: project
      nav_section: projects

exclude:
  - README.md
  - jekyll-theme.zip
